<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\osu.Game.Rulesets.Hikariii\osu.Game.Rulesets.Hikariii.csproj" />
      <ProjectReference Include="..\submodules\lazer-sandbox\osu.Game.Rulesets.Sandbox\osu.Game.Rulesets.Sandbox.csproj" PrivateAssets="all" ExcludeAssets="runtime"/>
    </ItemGroup>

</Project>
