<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\upstream_assets\osu.Android.props" />
    <PropertyGroup>
        <TargetFramework>net8.0-android</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	      <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\osu.Game.Rulesets.Hikariii\osu.Game.Rulesets.Hikariii.csproj" />
    </ItemGroup>

</Project>
