name: dotnet
on:
  push:
    branches: [ "ruleset" ]
  pull_request:
    branches: [ "ruleset" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet (${{ matrix.dotnet-version }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Resolve dependencies
        run: dotnet restore BuildHikariii

      - name: Build
        run: dotnet publish BuildHikariii -c Release

      - name: Copy README.md
        run: cp 'README.md' BuildHikariii/bin/Release/net8.0/publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            BuildHikariii/bin/Release/net8.0/publish/M.*.dll
            BuildHikariii/bin/Release/net8.0/publish/*/M.*.dll
            BuildHikariii/bin/Release/net8.0/publish/osu.Game.Rulesets.*.dll
            BuildHikariii/bin/Release/net8.0/publish/Tmds.*.dll
            BuildHikariii/bin/Release/net8.0/publish/*.md
            BuildHikariii/bin/Release/net8.0/publish/NetCoreServ*.dll
            !BuildHikariii/bin/Release/net8.0/publish/*.txt