name: Build
on:
  push:
    branches: ['ruleset', 'ci']
  pull_request:
    branches: ['ruleset']
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    env:
      ARTIFACT_PATH: |
        assemble-temp/*

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet (${{ matrix.dotnet-version }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Hikariii (Windows)
        run: dotnet publish BuildHikariii.Windows -c Release

      - name: Copy artifacts (Windows)
        run: |
          env COPYONLY=true ./package.sh BuildHikariii.Windows windows

      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: Hikariii.WindowsDesktop
          path: ${{ env.ARTIFACT_PATH }}

  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.424']

    env:
      ARTIFACT_PATH: |
        assemble-temp/*

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet (${{ matrix.dotnet-version }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Prepare .NET workload
        run: |
          cp global-android.json global.json || exit 1
          echo ".NET Version:"
          dotnet --version
          sudo dotnet workload restore || exit 2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ env.cache-name }}-android-sdk-${{ hashFiles('BuildHikariii.Android/BuildHikariii.Android.csproj') }}
          path: |
            ${{ env.HOME }}/.android/sdk
            ~/.android/sdk
            $HOME/.android/sdk

      # This defaults to ~/.android/sdk
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Build Hikariii (Android)
        run: dotnet publish BuildHikariii.Android -c Release -p:AndroidSdkDirectory="$HOME/.android/sdk"

      - name: Copy artifacts (Android)
        run: |
          env COPYONLY=true ./package.sh BuildHikariii.Android android

      - name: Upload artifacts (Android)
        uses: actions/upload-artifact@v4
        with:
          name: Hikariii.Android
          path: ${{ env.ARTIFACT_PATH }}

  build-common:
    name: Build Common
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    env:
      ARTIFACT_PATH: |
        assemble-temp/*

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet (${{ matrix.dotnet-version }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Hikariii (Common)
        run: dotnet publish BuildHikariii -c Release

      - name: Copy artifacts (Common)
        run: |
          env COPYONLY=true ./package.sh BuildHikariii

      - name: Upload artifacts (Common)
        uses: actions/upload-artifact@v4
        with:
          name: Hikariii.Desktop
          path: ${{ env.ARTIFACT_PATH }}
