name: Build
on:
  push:
    branches: ['ruleset', 'ci']
  pull_request:
    branches: ['ruleset']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    env:
      ARTIFACT_PATH: |
        tmp/M.*.dll
        tmp/*/M.*.dll
        tmp/LLin.*.dll
        tmp/osu.Game.Rulesets.*.dll
        tmp/Tmds.DBus.*.dll
        tmp/Microsoft.Windows.SDK.NET.dll
        tmp/WinRT.Runtime.dll
        tmp/README.md

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet (${{ matrix.dotnet-version }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Hikariii (Common)
        run: dotnet publish BuildHikariii -c Release

      - name: Copy artifacts (Common)
        run: |
          cp -r BuildHikariii/bin/Release/net8.0/publish tmp
          cp README.md tmp

      - name: Upload artifacts (Common)
        uses: actions/upload-artifact@v4
        with:
          name: common
          path: ${{ env.ARTIFACT_PATH }}

      - name: Build Hikariii (Windows)
        run: dotnet publish BuildHikariii.Windows -c Release

      - name: Copy artifacts (Windows)
        run: |
          rm -rf tmp
          cp -r BuildHikariii.Windows/bin/Release/net8.0*/publish tmp
          cp README.md tmp

      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ${{ env.ARTIFACT_PATH }}
